/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.principal;

import com.bean.Picklist;
import com.dao.PicklistJpaDAO;
import java.io.File;
import java.io.FileWriter;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author thiago.napoleao
 */
public class ArquivoCsv extends javax.swing.JFrame {
     
    /**
     * Creates new form ArquivoCsv
     */
    public ArquivoCsv() throws ParseException {
        initComponents();
         MaskFormatter maskData = new MaskFormatter("##/##/####");  
        maskData.install(dataTxt); 
    }
    
    public void relatorio(){
        boolean geraArq = false;
        
        File arquivo;
        String patch = "";
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        int x = file.showSaveDialog(null);
        if(x == 1){
            JOptionPane.showMessageDialog(null, "Nenhum arquivo selecionado!");
        }else{
            arquivo = file.getSelectedFile();
            patch = arquivo.getPath();
            patch +=".csv";
            geraArq = true;
        }
        if(geraArq){
            try{
                 FileWriter writer = new FileWriter(patch);
                 writer.append("Data");
                 writer.append(";");
                 writer.append("Rota");
                 writer.append(";");
                 writer.append("Roteiro");
                 writer.append(";");
                 writer.append("Picklist");
                 writer.append(";");
                 writer.append("volume");
                 writer.append(";");
                 writer.append("Hora");
                 writer.append(";");
                 writer.append("Auditor");
                 writer.append("\n");
                 
                 List<Picklist> pick = PicklistJpaDAO.getInstance().findByDataRota(dataTxt.getText(), rotaTxt.getText());
                 
                  for(int b = 0; b < pick.size(); b++) {
                     writer.append(pick.get(b).getDataauditada());
                     writer.append(";");
                     writer.append(pick.get(b).getRota());
                     writer.append(";");
                     writer.append(pick.get(b).getRoteiro());
                     writer.append(";");
                     writer.append(pick.get(b).getPicklist());
                     writer.append(";");
                     writer.append(pick.get(b).getVolume());
                     writer.append(";");
                     writer.append(pick.get(b).getHora());
                     writer.append(";");
                     writer.append(pick.get(b).getAuditor());
                     writer.append("\n");
                    
                }
                 writer.flush();
                 writer.close();
                 JOptionPane.showMessageDialog(null, "Arquivo Gerado com sucesso!");
                 ArquivoCsv.super.dispose();
            }catch(Exception e){
                e.printStackTrace();
            }       
        }           
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblH10 = new javax.swing.JLabel();
        dataTxt = new javax.swing.JFormattedTextField();
        lblH8 = new javax.swing.JLabel();
        rotaTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 33, 71));

        lblH10.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        lblH10.setForeground(new java.awt.Color(255, 255, 255));
        lblH10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblH10.setText("Data");
        lblH10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        dataTxt.setForeground(new java.awt.Color(0, 51, 102));
        dataTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataTxt.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        dataTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataTxtKeyReleased(evt);
            }
        });

        lblH8.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        lblH8.setForeground(new java.awt.Color(255, 255, 255));
        lblH8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblH8.setText("Rota ");
        lblH8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rotaTxt.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        rotaTxt.setForeground(new java.awt.Color(0, 51, 102));
        rotaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rotaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rotaTxtKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Fax", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Gerar Arquivo CSV");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblH8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(lblH10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblH10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblH8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        lblH10.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dataTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataTxtKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            try{
                rotaTxt.requestFocus();
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_dataTxtKeyReleased

    private void rotaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rotaTxtKeyReleased
     
    }//GEN-LAST:event_rotaTxtKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        relatorio();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArquivoCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArquivoCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArquivoCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArquivoCsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ArquivoCsv().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(ArquivoCsv.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dataTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblH10;
    private javax.swing.JLabel lblH8;
    private javax.swing.JTextField rotaTxt;
    // End of variables declaration//GEN-END:variables
}
