/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.principal;

import com.bean.Picklist;
import com.dao.PicklistJpaDAO;
import com.utils.Tabela;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author thiago.napoleao
 */
public class Consulta extends javax.swing.JPanel {

    /**
     * Creates new form Consulta
     */
    public Consulta() throws ParseException {
        initComponents();
        defaults();
       picklistTxt.requestFocus(true);      
    }

   
        
    public void defaults(){
       picklistTxt.requestFocus(true);     
    }
    
   
     public void preencherTabela() {
       
         
         try {
            ArrayList dados = new ArrayList();

            String[] Colunas = new String[]{"Picklist", "Volume", "Rota", "Roteiro", "Hora"};
            
            /////////////////////////////////////
            
            List<Picklist> prt = PicklistJpaDAO.getInstance().findByPicklist(picklistTxt.getText());

            for(int i = 0; i < prt.size(); i++) {

            dados.add(new Object[]{prt.get(i).getPicklist(), prt.get(i).getVolume(), prt.get(i).getRota(), prt.get(i).getRoteiro(), prt.get(i).getHora()});
            
            }

            Tabela tabela = new Tabela(dados, Colunas);
            tblConferencia.setModel(tabela);
            tblConferencia.setRowSorter(new TableRowSorter(tabela));
            
            tblConferencia.getColumnModel().getColumn(0).setPreferredWidth(120);
            tblConferencia.getColumnModel().getColumn(0).setResizable(false);
            
            tblConferencia.getColumnModel().getColumn(1).setPreferredWidth(90);
            tblConferencia.getColumnModel().getColumn(1).setResizable(false);
            
            tblConferencia.getColumnModel().getColumn(2).setPreferredWidth(90);
            tblConferencia.getColumnModel().getColumn(2).setResizable(false);
            
            tblConferencia.getColumnModel().getColumn(3).setPreferredWidth(90);
            tblConferencia.getColumnModel().getColumn(3).setResizable(false);
            
            tblConferencia.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblConferencia.getColumnModel().getColumn(4).setResizable(false);
            
      
        
            tblConferencia.getTableHeader().setReorderingAllowed(false);
            tblConferencia.setAutoResizeMode(tblConferencia.AUTO_RESIZE_OFF);
            tblConferencia.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
            
        }catch(Exception ex) {
            ex.printStackTrace();
        } 
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblH1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConferencia = new javax.swing.JTable();
        picklistTxt = new javax.swing.JTextField();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(18, 33, 71));

        lblH1.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        lblH1.setForeground(new java.awt.Color(255, 255, 255));
        lblH1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblH1.setText("Picklist");
        lblH1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tblConferencia.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        tblConferencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblConferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblConferencia.setGridColor(new java.awt.Color(255, 255, 255));
        tblConferencia.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblConferencia);

        picklistTxt.setFont(new java.awt.Font("Lucida Fax", 2, 14)); // NOI18N
        picklistTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                picklistTxtKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Consulta Picklist Auditado");

        jDesktopPane5.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Lucida Fax", 1, 55)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logo1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/logo15.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(picklistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addComponent(jDesktopPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblH1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(picklistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(24, 24, 24))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void picklistTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_picklistTxtKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){            
            preencherTabela();
        }
    }//GEN-LAST:event_picklistTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblH1;
    private javax.swing.JTextField picklistTxt;
    private javax.swing.JTable tblConferencia;
    // End of variables declaration//GEN-END:variables
}
